### ISSUE TITLE
Ssh agent-forwarding problems in detached tmux session

### ISSUE THREAD

**Issue by hanefi** [citusdata/test-automation#93]
When I try to run a test in enterprise repo in a detached tmux session, fab fails to use my ssh keys and it errors out.

```
[localhost] run: git clone -q git@github.com:citusdata/citus-enterprise.git /home/ec2-user/citus-enterprise
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/paramiko/agent.py", line 114, in run
    self._communicate()
  File "/usr/lib/python2.7/dist-packages/paramiko/agent.py", line 124, in _communicate
    events = select([self._agent._conn, self.__inr], [], [], 0.5)
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by hanefi** [comment]
Apparently, this is a known issue of using a combination of ssh agent-forwarding and tmux (or similarly screen). A possible workaround that seems to work for me is here: https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
